### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by YAKUDZAIt18** [openpim/web#11] opened 2022-11-18 08:24 UTC
Are dialog forms work fine?
When i click on any item dialogs opens, and i can't close it
Can this be fixed somehow?

**Comment by openpim** [comment] 2022-11-18 10:29
Hi, can you please send the screenshot what you have at the screen?

**Comment by YAKUDZAIt18** [comment] 2022-11-18 10:36
![Снимок экрана 2022-11-18 133501.png](https://user-images.githubusercontent.com/80626791/202683495-95d39bcc-83be-44e3-a6a6-58034fa87c70.png)

**Comment by openpim** [comment] 2022-11-18 11:48
looks strange, seems something is wrong in the system that you have this. Probably you have wrong version or configuration. Can you please drop me an email to team@openpim.org, we can arrange a call where you can share the screen and we can try to resolve this.

**Comment by openpim** [comment] 2022-11-20 13:38
closing it because we can not reproduce this. Please send me an email if you still have this behaviour

**Closed as completed by openpim** 2022-11-20 13:38 UTC
